name: 'Roll latest packages'

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: windows-2019

    steps:
    - name: Git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global user.email "gpgmm-autoroll@users.noreply.github.com"
        git config --global user.name "GPGMM Autoroller"

    - name: Install depot_tools
      shell: cmd
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ..\depot_tools
        set "PATH=%CD%\..\depot_tools;%PATH%"
        gclient

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Sync code for main branch
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        copy scripts\standalone.gclient .gclient
        gclient sync

    - name: Roll jsoncpp/source
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        roll-dep third_party/jsoncpp/source

    - name: Commit changes
      shell: cmd
      run: |
        git push
